TRUNCATE TABLE find_log;
TRUNCATE TABLE horserace_log;
TRUNCATE TABLE horserace_play;
TRUNCATE TABLE carrace_log;
TRUNCATE TABLE carrace_play;
TRUNCATE TABLE spot_log;
TRUNCATE TABLE spot_consume_log;
TRUNCATE TABLE turntable_log;
TRUNCATE TABLE turntable_play;